import { Account } from './types'

export const accounts: Account[] = [
  {
    id: 'harmon-associates',
    name: 'Harmon & Associates',
    industry: 'Legal',
    arr: 320000,
    health: 'red',
    riskScore: 79,
    sentimentScore: 18,
    dataHealthScore: 41,
    profileCompleteness: 15,
    priority: 'P0',
    renewalMonths: 2,
    keySignals: ['48-day non-response', 'No documented business goals', 'Strategy meeting declined', 'Renewal in 2 months'],
    notes: 'Most urgent account. Silent for 48 days, renewal approaching. No champion identified post-partner change.',
    mspTurningPoint: {
      marginContribution: 14,
      status: 'below',
      note: 'High recovery effort on a disengaged account — reactive hours exceed contracted scope. Below turning point.',
    },
    valueSnapshot: {
      technicalSignal: 'Autotask shows 0 strategic meeting completions in last quarter. IT Glue contact list stale — 2 key contacts departed. Thread triage volume down 60% suggesting disengagement, not stability.',
      businessOutcome: 'Client silence ahead of renewal is a churn precursor pattern. No documented goals means no defensible value story. $3.2M MRR contract at immediate risk with no internal advocate.',
      outcomeCategory: 'Risk Mitigation',
      dollarValue: '$3.2M',
      sources: ['Autotask', 'IT Glue', 'Thread'],
      confidence: 'high',
    },
    redFlagSignal: {
      type: 'silent',
      description: 'No response to 3 outreach attempts over 48 days. Last Fathom note tone was neutral. Strategy meeting request declined twice.',
      daysSinceContact: 48,
      lastTone: 'neutral',
    },
    blockerMatch: {
      blocker: 'Partner-level contact departed. No replacement champion. Account silent ahead of renewal.',
      solution: 'Sent a personalised business review video referencing a specific IT milestone from their last strategy meeting. Followed by a structured 2-week re-engagement sprint with the incoming partner.',
      resolvedBy: 'TurboTek Account Recovery Playbook — Jan 2025',
      matchConfidence: 87,
    },
  },
  {
    id: 'crestview-medical',
    name: 'Crestview Medical Group',
    industry: 'Medical',
    arr: 380000,
    health: 'red',
    riskScore: 74,
    sentimentScore: 22,
    dataHealthScore: 45,
    profileCompleteness: 20,
    priority: 'P0',
    keySignals: ['HIPAA compliance gap flagged', 'P1 ticket surge', 'New Office Manager', 'Missed QBR'],
    notes: 'Compliance concern blocking strategic progress. New office manager unfamiliar with existing roadmap.',
    mspTurningPoint: {
      marginContribution: 10,
      status: 'below',
      note: 'P1 surge driving unplanned support hours. Compliance remediation adds further cost-to-serve. Below turning point.',
    },
    valueSnapshot: {
      technicalSignal: 'Autotask P1 tickets up 140% over 30 days — majority related to EHR access failures. Thread flagged 3 compliance-adjacent issues unresolved for 18+ days. IT Glue shows no updated HIPAA documentation since 2023.',
      businessOutcome: 'Unresolved HIPAA compliance gap creates regulatory exposure and erodes client trust. Estimated $220K remediation cost if audit triggered. New office manager has no context on current roadmap — relationship reset required.',
      outcomeCategory: 'Compliance',
      dollarValue: '$220K exposure',
      sources: ['Autotask', 'Thread', 'IT Glue'],
      confidence: 'high',
    },
    redFlagSignal: {
      type: 'critical',
      description: 'P1 surge with compliance overtones. New office manager unresponsive since missed QSR 14 days ago.',
      daysSinceContact: 14,
      lastTone: 'frustrated',
    },
    scopeDrift: {
      description: 'New office manager requested custom EHR audit trail with 90-day retention in MS Teams thread. Current SOW covers 30-day standard retention only.',
      sowReference: 'SOW Section 3.1 — Standard audit logging, 30-day retention',
      source: 'MS Teams · Feb 18',
      flaggedDaysAgo: 3,
    },
    blockerMatch: {
      blocker: 'HIPAA compliance gap escalating with new management contact, no one owns resolution internally.',
      solution: 'Scheduled emergency 30-min triage call with practice administrator bypassing helpdesk. Created a compliance action plan within 48 hours. Resolved in 7 days.',
      resolvedBy: 'TurboTek Compliance Fast-Track — Oct 2024',
      matchConfidence: 90,
    },
  },
  {
    id: 'valley-fabrication',
    name: 'Valley Fabrication Inc.',
    industry: 'Manufacturing',
    arr: 240000,
    health: 'red',
    riskScore: 71,
    sentimentScore: 25,
    dataHealthScore: 38,
    profileCompleteness: 18,
    priority: 'P0',
    keySignals: ['Network refresh overdue 3+ years', 'Backup failure detected', 'No strategy roadmap documented', 'IT lead resistant'],
    notes: 'Infrastructure risk account. Overdue refresh creating operational exposure. Sean has been raising this for 2 quarters.',
    mspTurningPoint: {
      marginContribution: 16,
      status: 'below',
      note: 'Recurring infrastructure failures generating high reactive ticket volume. Below turning point until refresh is resolved.',
    },
    valueSnapshot: {
      technicalSignal: 'Kaseya RMM alerts show 3 unresponsive switches for 11 days. Backup job failures logged in Autotask for 6 consecutive weeks. IT Glue network diagram last updated 2021. Thread flagged recurring connectivity tickets.',
      businessOutcome: 'Network infrastructure 3+ years past recommended refresh cycle. Active backup failures mean zero recovery capability in a ransomware event. IDC estimates mid-market manufacturers lose $180–240K/month during unplanned downtime events.',
      outcomeCategory: 'Risk Mitigation',
      dollarValue: '$180–240K/month downtime exposure',
      sources: ['Kaseya RMM', 'Autotask', 'IT Glue', 'IDC'],
      confidence: 'high',
    },
    redFlagSignal: {
      type: 'cold',
      description: 'IT lead resistant to refresh conversations. CFO last contacted 22 days ago. Sean has raised network refresh on 2 consecutive QSRs with no sign-off.',
      daysSinceContact: 22,
      lastTone: 'resistant',
    },
    blockerMatch: {
      blocker: 'CFO resistant to network refresh investment despite documented risk. No third-party validation to back the recommendation.',
      solution: 'Provided IDC research brief on infrastructure lifecycle cost vs. downtime risk. Framed as fiduciary responsibility. CFO approved within 2 weeks.',
      resolvedBy: 'TurboTek Infrastructure Advisory Playbook — Mar 2025',
      matchConfidence: 88,
    },
  },
  {
    id: 'northshore-orthopedics',
    name: 'Northshore Orthopedics',
    industry: 'Healthcare',
    arr: 280000,
    health: 'yellow',
    riskScore: 55,
    sentimentScore: 42,
    dataHealthScore: 56,
    profileCompleteness: 38,
    priority: 'P1',
    keySignals: ['Windows 10 EOL not resolved', 'Budget freeze', 'Champion stretched thin', 'Adoption stalled'],
    expansionPotential: { low: 48000, high: 72000 },
    notes: 'Windows 10 EOL remediation stalled due to budget freeze. Security exposure growing.',
    mspTurningPoint: {
      marginContribution: 36,
      status: 'at',
      note: 'Moderate ticket volume with OS-related spikes. At the turning point — EOL resolution would push this account into pure profit territory.',
    },
    valueSnapshot: {
      technicalSignal: 'Kaseya RMM shows 34 endpoints still on Windows 10 (EOL Jan 2025). Autotask ticket volume for OS-related issues up 55%. IT Glue asset list shows no refresh plan documented for 18 workstations.',
      businessOutcome: 'HIPAA-regulated environment running unsupported OS. Each unpatched endpoint is a compliance liability. Forrester estimates healthcare orgs with unpatched endpoints face 2.4x higher breach probability. Remediation blocked by budget freeze — not technical complexity.',
      outcomeCategory: 'Compliance',
      dollarValue: '$480K–720K remediation + risk exposure',
      sources: ['Kaseya RMM', 'Autotask', 'IT Glue', 'Forrester'],
      confidence: 'high',
    },
    scopeDrift: {
      description: 'Office manager requesting endpoint migration project management as part of standard support agreement. SOW covers break-fix only, not project delivery.',
      sowReference: 'SOW Section 2.1 — Reactive support only',
      source: 'Fathom · Feb 12',
      flaggedDaysAgo: 6,
    },
  },
  {
    id: 'lakeview-logistics',
    name: 'Lakeview Logistics',
    industry: 'Manufacturing',
    arr: 260000,
    health: 'yellow',
    riskScore: 48,
    sentimentScore: 46,
    dataHealthScore: 53,
    profileCompleteness: 30,
    priority: 'P1',
    keySignals: ['ERP integration stalled', 'New IT contact', 'No business goals documented', 'Single point of contact'],
    expansionPotential: { low: 36000, high: 60000 },
    notes: 'Transition state after IT contact change. New contact not onboarded to strategic roadmap.',
    mspTurningPoint: {
      marginContribution: 31,
      status: 'at',
      note: 'ERP stall driving manual workaround tickets. At the turning point — integration resolution would stabilise cost-to-serve.',
    },
    valueSnapshot: {
      technicalSignal: 'Autotask shows ERP sync tickets unresolved for 19 days. Thread AI recommended middleware fix — not yet actioned by client. IT Glue notes reference manual workarounds for inventory data that should be automated.',
      businessOutcome: 'ERP integration stall means manual data entry for inventory management — IDC estimates this costs mid-market logistics firms $90–130K/year in operational overhead. New IT contact has no visibility into prior commitments.',
      outcomeCategory: 'Operational',
      dollarValue: '$90–130K/year manual overhead',
      sources: ['Autotask', 'Thread', 'IT Glue', 'IDC'],
      confidence: 'moderate',
    },
    blockerMatch: {
      blocker: 'ERP middleware compatibility issue unresolved after 3 weeks. New IT contact not empowered to approve the fix.',
      solution: 'Escalated directly to operations director with a 1-page business case showing cost of delay. REST adapter workaround deployed in 4 days.',
      resolvedBy: 'TurboTek ERP Fast-Track Playbook — Nov 2024',
      matchConfidence: 83,
    },
  },
  {
    id: 'meridian-dental',
    name: 'Meridian Dental Partners',
    industry: 'Medical',
    arr: 220000,
    health: 'yellow',
    riskScore: 38,
    sentimentScore: 55,
    dataHealthScore: 61,
    profileCompleteness: 52,
    priority: 'P2',
    keySignals: ['Stable usage', 'Low strategic engagement', 'Single contact', 'Transactional relationship'],
    expansionPotential: { low: 28000, high: 44000 },
    notes: 'Operationally stable but shallow relationship. No documented business goals. Expansion possible with deeper engagement.',
    mspTurningPoint: {
      marginContribution: 54,
      status: 'above',
      note: 'Low ticket volume and predictable support pattern. Comfortably above turning point — pure profit contribution.',
    },
    valueSnapshot: {
      technicalSignal: 'Autotask shows consistent low ticket volume for 5 months — no P1/P2 incidents. Kaseya RMM patch compliance at 89%. IT Glue documentation completeness at 72%. No strategy meeting held in 6 months.',
      businessOutcome: 'Stable delivery is a foundation, not a moat. No strategic roadmap means no stickiness story. Forrester dental practice benchmarks show practices with documented IT roadmaps have 40% lower churn from MSPs.',
      outcomeCategory: 'Risk Mitigation',
      dollarValue: '40% lower churn risk with roadmap',
      sources: ['Autotask', 'Kaseya RMM', 'IT Glue', 'Forrester'],
      confidence: 'moderate',
    },
  },
  {
    id: 'graham-chambers',
    name: 'Graham Chambers LLP',
    industry: 'Legal',
    arr: 360000,
    health: 'green',
    riskScore: 22,
    sentimentScore: 78,
    dataHealthScore: 82,
    profileCompleteness: 85,
    priority: 'expand',
    renewalMonths: 7,
    keySignals: ['Strong partner relationship', 'High engagement', 'Renewal in 7 months', 'Cyber audit interest'],
    expansionPotential: { low: 54000, high: 86000 },
    notes: 'Healthiest legal account. Managing partner actively engaged. Natural vehicle for cybersecurity expansion.',
    mspTurningPoint: {
      marginContribution: 66,
      status: 'above',
      note: 'Zero P1/P2 incidents in 7 months. Highly predictable, low-touch account. Strong pure profit contributor.',
    },
    valueSnapshot: {
      technicalSignal: 'Autotask: zero P1/P2 incidents in 7 months. IT Glue profile 85% complete. Fathom notes from last QSR reference managing partner asking about cyber liability insurance requirements. Kaseya RMM patch compliance 97%.',
      businessOutcome: 'Outperforming peer benchmark on stability. Managing partner\'s cyber insurance question is a direct entry point for a security audit engagement. Forrester Legal: firms with documented security posture renew MSP contracts at 2.8x rate.',
      outcomeCategory: 'Revenue Impact',
      dollarValue: '$540K–860K expansion',
      sources: ['Autotask', 'IT Glue', 'Fathom', 'Kaseya RMM', 'Forrester'],
      confidence: 'high',
    },
  },
  {
    id: 'pinnacle-health',
    name: 'Pinnacle Health Systems',
    industry: 'Healthcare',
    arr: 340000,
    health: 'green',
    riskScore: 18,
    sentimentScore: 83,
    dataHealthScore: 85,
    profileCompleteness: 90,
    priority: 'expand',
    renewalMonths: 9,
    keySignals: ['QSR next month', 'High adoption', 'Strong champion', 'Telehealth expansion planned'],
    expansionPotential: { low: 68000, high: 110000 },
    notes: 'Strongest account in portfolio. COO is an active champion. Telehealth initiative creates a concrete expansion opportunity.',
    mspTurningPoint: {
      marginContribution: 71,
      status: 'above',
      note: 'Highest margin account in portfolio. 98% patch compliance, zero reactive incidents — textbook above turning point.',
    },
    valueSnapshot: {
      technicalSignal: 'Kaseya RMM: 98% patch compliance, zero critical alerts in 90 days. Autotask: satisfaction score 4.9/5 over last 3 QSRs. Fathom notes: COO referenced telehealth expansion plans 3 times in last 60 days. IT Glue 90% complete.',
      businessOutcome: 'Highest-health account in portfolio. COO\'s telehealth initiative requires secure remote access infrastructure and HIPAA-compliant endpoint management — both within TurboTek\'s wheelhouse. QSR next month is the natural expansion vehicle.',
      outcomeCategory: 'Revenue Impact',
      dollarValue: '$680K–1.1M expansion',
      sources: ['Kaseya RMM', 'Autotask', 'Fathom', 'IT Glue'],
      confidence: 'high',
    },
  },
]

export const portfolioStats = {
  totalArr: 2400000,
  totalAccounts: 8,
  p0Arr: 940000,
  p1Arr: 760000,
  stableArr: 220000,
  expansionArr: 700000,
  expansionLow: 234000,
  expansionHigh: 372000,
  nearTermExpansionLow: 122000,
  nearTermExpansionHigh: 196000,
}
